name: Update Weather Data
on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜 00:00 触发任务
  workflow_dispatch:  # 手动触发选项

jobs:
  update-weather:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 运行 Python 脚本
      - name: Run weather.py
        run: |
          python weather.py

      # 提交并推送更新后的文件到 GitHub
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update weather data'
          repository: ./
          branch: main
          file_pattern: '成都天气.csv'
          # 需要使用个人访问令牌
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 添加 Slack 通知（可选）
      # 如果需要通知，可以添加以下步骤
      - name: Notify on Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Weather data updated automatically!"}' $SLACK_WEBHOOK_URL
